chore(ui): connectrpc migrate to version 2
akuity/kargo pull request #3072
Opened 2024-12-05 20:54 UTC by Marvin9

Migration guide that was followed: https://github.com/connectrpc/connect-es/blob/main/MIGRATING.md

Verified with basic operations and the area that code change touches and fix all the potential issues.

Notable changes:

- No more manual patch to generated proto classes. It was used to get `Date` type from `google.protobuf.Timestamp` type. Now its explicit function `k8sApiMachineryTimestampDate`.
- API was changed to generate query.. this still needs better way to figure out how to do it
- There is now `PlainMessage` equivalent homegrown implementation that just works

2024-12-09 15:25 UTC, Marvin9 commented
@rpelczar can I get some eyes on it please?

2024-12-10 00:26 UTC, rpelczar requested changes

2024-12-10 00:26 UTC, rpelczar commented on ui/src/features/common/commit-info.tsx
> +export const CommitInfo = ({ commit }: { commit: PlainMessage<GitCommit> }) => (
I understand the purpose of having PlainMessage, but in some places, it seems redundant.
This is an example.

2024-12-10 00:26 UTC, rpelczar commented on ui/src/utils/connectrpc-extension.ts
> +export const k8sApiMachineryTimestampDate = (t?: Time | PlainMessage<Time> | string) => {
Can we find a better name for it? Do we use it for all dates or just selected ones?

2024-12-10 00:26 UTC, rpelczar commented on ui/src/utils/connectrpc-extension.ts
Can we name it `connectrpc-utils.ts`?

2024-12-11 14:51 UTC, rpelczar approved these changes
LGTM!

2024-12-16 17:04 UTC, krancour approved these changes

2024-12-19 17:14 UTC, merged