Apply revive lint rules
akuity/kargo pull request #580
Opened 2023-08-18 03:02 UTC by devholic

Apply project-wide lint rules for consistency.

2023-08-18 05:24 UTC, gdsoumya requested changes

2023-08-18 05:24 UTC, gdsoumya commented on internal/cli/login/login.go
> +				_, _ = fmt.Print(
These seem a bit too verbose?

2023-08-18 18:42 UTC, rbreeze approved these changes
LGTM

2023-08-21 04:12 UTC, gdsoumya approved these changes

2023-08-21 04:28 UTC, merged